// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Automation Report",
  description: "Generated by create next app",
};

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <head>
//         <meta name="description" content={metadata.description || undefined} />
//       </head>
//       <body className={inter.className}>
//         <nav className="navbar">
//           <p className="navbar-text">Dashboard</p>
//           <div className="navbar-title">Playwright Automation Report</div>
//         </nav>
//         <main>{children}</main>
//       </body>
//     </html>
//   );
// }
// layout.tsx
import type { Metadata } from "next";
import "./globals.css";

const Layout = ({ children }: Readonly<{ children: React.ReactNode }>) => {
  return (
    <html lang="en">
      <head>
        <meta name="description" content={metadata.description || undefined} />
      </head>
      <body className="font-inter bg-[#F7F7F7] ">
        <nav className="navbar flex justify-between items-center bg-gray-100 border-b border-gray-300 px-4 py-2">
          <p className="navbar-text text-lg text-[#73879C]">Dashboard</p>
          <div className="navbar-title text-lg text-[#73879C]">Playwright Automation Report</div>
        </nav>
        <main className="p-4">{children}</main>
      </body>
    </html>
  );
};
//font-size: 18px;
// height: 50px;
// margin-bottom: 0;
// margin-top: 0;
// padding: 15px 0;
export default Layout;

